repos:
  -   repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
      -   id: flake8
          exclude: ^env/
  -   repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
      -   id: black
          exclude: ^env/