app_container_image: "yesliesnayder/app_python:1.0.6"
app_container_name: app_python
service_name: "{{ app_container_name }}"

app_container_ports:
  - "8000:8000"

web_app_full_wipe: false

app_visits_file: ./app_python_data