---
- name: Stop and Remove Docker container
  when: web_app_full_wipe
  block:
    - name: Check if Docker Compose exists
      stat:
        path: "{{ docker_compose_path }}"
      register: compose_file_status
    - name: Stop Docker Compose
      command: "docker-compose -p {{ app_name }} stop"
      args:
        chdir: "{{ app_dir }}"
      when: compose_file_status.stat.exists == true
    - name: "Remove {{ app_name }} directory"
      file:
        path: "{{ app_dir }}"
        state: absent
    - name: Remove Docker container
      community.docker.docker_container:
        name: "{{ docker_container }}"
        state: absent
    - name: Remove Docker image
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_version }}"
        state: absent