[type_vkcs_compute_floatingip_associate]

[vk_cloud:children]
type_vkcs_compute_floatingip_associate

[vk_cloud:vars]
ansible_user=ubuntu

[vk_cloud]
ubuntu@95.163.180.234 ansible_ssh_private_key_file=~/.ssh/id_rsa