apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app_python
  template:
    metadata:
      labels:
        app: app_python
    spec:
      containers:
        - name: minikube
          image: rinnatova/docker_lab:latest
          ports:
            - containerPort: 8080
