password: ENC[AES256_GCM,data:y97RMiNBTK4aBXrotPc5wsD+,iv:GURI75qkMJ3HtmDShrYaeTy/cetnI3FjA0SFKzqdCd4=,tag:mIL//mZVkZSp9VzbCh2ZVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-14T17:47:02Z"
    mac: ENC[AES256_GCM,data:zGJyNc3IexHP6k3udBykc2UhcLkr7sYLGgbW5LrgDRGHuWL/8Yo/LXYZjbIJ1cdV2l80AdSZ4bFHSLv143FPfneVFZ1/3s+Bxay9DbWNsAne+dcfRrumDY2tQlOz6tO+9Ryh3j1A2ATI+dogyDO5ygE0f5LETc3d6Ha7uE1LSgQ=,iv:6cpUwxWDwFKFvKB7MVWIKymnYTQHTFAdoX6xObFpxrA=,tag:Nq9VeK+J/uA334AJClMr2w==,type:str]
    pgp:
        - created_at: "2023-11-13T17:49:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----
            hF4DSF6O9fWZSd4SAQdAWJ+T1EtHo4H9OZma+5ceEqY2rCrF4ABZvZE0EFS8Uicw
            Hq1j5uhakNz+cw4Yx9CLz3yOawWKE50yFhmvDK3s5ab6opn3H1MB/brudCnOlSta
            1GYBCQIQqBB+5QL4ZYuWWD5+teUYRgr1ZfYfLWOt2WrVsFMx/g60IHTmorq0ko+3
            XeoiV8REPcCb70LPVjjocQbOoSa6BssFJCf4XRjsBEhRtD0d5Oe9Bau2Mupq/Za5
            49/cjvOiH4c=
            =fOWW
            -----END PGP MESSAGE-----
          fp: 4FA6770E23AF2B6095DFB9AB207B26D1141A0C77
    unencrypted_suffix: _unencrypted
    version: 3.8.1