password: ENC[AES256_GCM,data:c6X/m1ug1Y2c2Q==,iv:hJw5Np282DHZY3byT0x/vOCuOEoS7LDfdz0FCndKggU=,tag:DdF5tziakZZl8AbdfKHHeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-14T18:47:01Z"
    mac: ENC[AES256_GCM,data:nCt0EGibA02l4B1PMBk6xXCYmSpu5pmABgrjWtMM8guVIfwRDjcgnNvKL9A/HyZojrppJK3GWXsLA42h0AHd90MGPu5ji6svWUkHSfJNomuXkl+XK5fkroMfreuASnlK5QE/6p4rRvbMpq70ez4K0WiwunCr+u5MD+PIvslAD+4=,iv:AVBwCdguyhvL7sLEUgF1z9cviqrtWxhNehOCiUo/Cyo=,tag:akHPK1Nzomz/dxu7fSIN0w==,type:str]
    pgp:
        - created_at: "2023-11-14T18:46:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA3884a/H3AIxAQwAsdv8KA+TOtuWAHgvBg0sohXtrPgATsWzh/1/Jh9v+ztH
            jlIaGYNphsec8Fcl97JVGEESUaOPPOboab14Xi1MIULnjJmZBGHY1QM19vcLHbD5
            pQiKtE57UzyA8tT1JZw9AsVKIjn2G/arX7TiRxeqkEhWgrU6zpBAw7hMrUV5mRcc
            ok3SuIdVZMwhDteDmdI90wa2PvJ1PtzD97wmaTsUxWcbyuERCBtfuq4bEaewqOdT
            4qYpJo6mOImu5uiDHNtogy4cRmps3N5N1vdIBMl5fsxSl1PlAdQfjNsjo0MpKOtY
            EUGEezlkasQvdroJ3plP9IBusbx09ORBemHa5EpckvHSWpsGQwuULBQJ/Y8vJOFU
            oBIHET9O78U+7njccmKm+WmUNbuY7pe2chAVzoy2k+URXO1iOI990N0KKmYA8M2G
            iNPD5LqGhkalR+7d/KGIGmIP1TN/frsPxFAudPiF1sD62azGAqDETdVpA7cjyKty
            waKpiCb/clM4Htk+tfo10lwBy6xKQe50wb8U5QkmINYiKSezjIqAdrAj89ETv0dK
            GSm1gsTjQMd/wIKOXKUDDJgJTC/3ZTJkw5sK7dqsI/nH1Adlrz1Os3g72uHbaHsT
            eG4C/Ss6epj4LAAcWg==
            =Jdmn
            -----END PGP MESSAGE-----
          fp: D5495900318DACCABE76BEE24B1339F1F95A55B2
    unencrypted_suffix: _unencrypted
    version: 3.8.1
