password: ENC[AES256_GCM,data:EDVgKvv2pmhrWq1m3xy9DeXF,iv:oiD/cPFDNZBrCsvAsqPpPjnJdP9SXNJr1zbpMG12EUM=,tag:jxAz+4eD6PyQHCqWLAf8Ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-22T00:25:10Z"
    mac: ENC[AES256_GCM,data:qaAmQGjrGLc3YRF5G0cxe2UXeZcMC69l1Si0NR431qOfw976qjOngP2drsLfACKW8912pfpG0wWgdBbpb/4WgJ83V4Dgve0DtP7a5hI37rYNuZruqnBhTS+AkFTGi81bqREILXuECGp5/SvfiOBjBmciNxtESdM6Q7HfOxTUwDY=,iv:rJ7yRKXxW3/6zlqdY+JPLqWh4iwWhQoECQCx/MoHUPQ=,tag:VHKlMmw6AGmWkYM0HDWmEg==,type:str]
    pgp:
        - created_at: "2023-11-22T00:24:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D7Yau7NkB22kSAQdA1OvW5JgTYcVSZoqOOY9i1sdCPPmeFANRIE+/6ClCnWsw
            Uiowyspz4xybXbX3DpQdIqHfWqoo/g+dbsjH4QKvcMNVtVahjltMD1O74jE9Gmop
            1GgBCQIQLq7igaJLaXvC2p2SkoDumwGlaR+DjgYa9GswtHn3941BCetAGaxyNl5j
            IxNuhse1JpRSdMAJsOY9tNaDd6NuFvrEhLa6mcqXmGWZa9f1qhU/lVs7Xdq3v5o2
            NVdOrADiQOmjrQ==
            =f2TY
            -----END PGP MESSAGE-----
          fp: C661F2C4D840206EFBF39B8F849FB8F1F877B1DC
    unencrypted_suffix: _unencrypted
    version: 3.8.1
