apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app.kubernetes.io/name: python-app
spec:
  selector:
    app.kubernetes.io/name: python-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
