apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  labels:
    app: app-python
    {{- include "library-chart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app-python
      {{- include "library-chart.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app: app-python
        {{- include "library-chart.labels" . | indent 8 }}
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: app-python
          image: ilyasiluyanov/app_python:dev
          imagePullPolicy: Always
          command: ["sleep"]
          args: ["100500"]
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: lab12-config
              mountPath: /app-python/config.json
              subPath: config.json
            - name: visits-storage
              mountPath: /app_python/visits
              subPath: visits

      volumes:
        - name: lab12-config
          configMap:
            name: lab12-config
        - name: visits-storage
          persistentVolumeClaim:
            claimName: visits-pvc