apiVersion: v1
kind: ConfigMap
metadata:
  name: app-python-config-map
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4}} 