global:
  scrape_interval: 5s

scrape_configs:
  # Python app
  - job_name: app_python
    static_configs:
      - targets: [app_python:5000]

  # Loki
  - job_name: loki
    static_configs:
      - targets: [loki:3100]

  # Promtail
  - job_name: promtail
    static_configs:
      - targets: [promtail:9080]

  # Grafana
  - job_name: grafana
    static_configs:
      - targets: [grafana:3000]

  # Prometheus
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]