apiVersion: v2
name: app-python
description: Chart for python fast api app
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: library-chart
    version: 0.1.0
    repository: file://../library-chart