token: ENC[AES256_GCM,data:oxli5Bk0NKJeRsnW,iv:ab9dffsce+sqHKrtUdJlxhEr2vd6BFnqDazYtY=,tag:7WH4Uwk4GraH6/K2BUL+Jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2023-11-13T23:26:01Z'
    mac: ENC[AES256_GCM,data:Qj51CaQwo7nT1/m1UptEoiup8AiQizgQbO6GSpJT3nf/2fv0CTvZ/jx3GQFEBo9F2u6OwYjd2IPLs975s0blUNnZO9Eed6lOt7+qZKWEQwNai+VeOrNV5nFuK5K5ptC8oe/nfCo+tc8OYJYeNPHxhL488hpOV2dhsjFLnWUy6Wo=,iv:nXwF/B4dheIrxyYlxyUmqfqUHv9JA31RqZSLp/MB3eg=,tag:lqKpjoxpsGGqn5VhOeIBnw==,type:str]
    pgp:
    -   created_at: '2023-11-13T23:25:43Z'
        enc: |
            -----BEGIN PGP MESSAGE-----
            hQGMA+V+6D8c5Kz1AQv7BoQZbWMWyve5bJ+gWBXW6bJ06MFaQ9E+ypVvLBujC0ds
            Hs0uLEr8i8FL30cgs83Lbv19CnAvjeSCp/akXc6rF4NmKrPU13C2E5GuHy8/FrNU
            goBj8/Bowr9A4vav8fgGnL2wmzhw8/V4tvMDoVYFuF6Eu/SFq0bjhknVmwMns
            CWhVElF5DbIUzJRv6HPM8s1sL1O7isyIfWHUOSpAoQSVxgu7lgykMNaCnV8WDzbW
            yvYrOvbbAhpv5brxKaFuvppf/FAsGoKgj5kD6D2YOak2ZWfoiHkGl/EWDzUT2ENy
            eBWsabhfTy78UTBTXDNzaNrVUnI7fzGgu6ciBYoZXFieS1NpeNZ0X4GPi7jO+us
            FHi3MZh1wYP3Gfdgs&tsUjHouEUqpqvjGSnKJXPpbaC2ohClusE2T2qlhdL
            AaH4exug9KfeD9EYIQCUYmRWDZOJxBRbVKEdj6WqQgnxqtQKJLaVooXU7Of1I93a
            S+UM3Ti4Z+ZSFWXRp+lW0l4B3xXddOO6xofgnRxeZiyI+Og3QnVtaSNO0zDOPx2f
            HXKG1eRtKIHczrK9CddoQ4vLh35S/vbJsZoy568ETIAz3+1Y5trrB/nr/l3m2xYJ
            iku694FDKoMrhDewezFQ
            =FQ9J
            -----END PGP MESSAGE-----
        fp: 4555BA4744CBAE3E487A0AA2DE1BA61777A6CCE9
    unencrypted_suffix: _unencrypted
    version: 3.0.3