# Uses apt because it is pre-installed on Debian / Ubuntu
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#ansible-collections-ansible-builtin-apt-module
- name: Update apt
  ansible.builtin.apt:
    update_cache: true

# Uses apt
- name: Install python
  ansible.builtin.apt:
    name:
      - python3
    state: present

# Uses apt
- name: Install pip
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present