MY_SECRET: ENC[AES256_GCM,data:FUIXS+dEtC9Z4AWfrc4=,iv:2TPCSkTbfkeifFwodl5tfTuFLmZMaF/+Afwmvhy0AFM=,tag:0iivWjMH08l7N92BmbOgUw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2023-11-10T18:06:32Z"
  mac: ENC[AES256_GCM,data:uaRaOirC2xJwMNwOxvx4h6w2O9O8azfWO4feF4wsCR/rYT5Q+Trk7Yc9CqXDqw2PbaSWM0I0ATYz/sjLR6PFYqG4odiHHduOABdS9TBbIUILSY4jnRbd3hEY3lQqd0kQVhks/jJJR6fs8mZPzx2OTJD0TEYAezW9z8FIdbH4dLg=,iv:7F+PXzNWXI40vMsijw4QuHOjt0JkdDUPGaWkPwlPuww=,tag:n9Do7Y3SO4Gz1XMFmceRbA==,type:str]
  pgp:
    - created_at: "2022-11-14T22:53:46Z"
      enc: |
        -----BEGIN PGP MESSAGE-----
        wF4DuomCmiUbyDISAQdANoA3Kyj8RlcE19Ngi4VACU5YqtwzF2HzWQV54ZQhsnkz
        shnRIYJkr4ROMIC5o8cTbAquZ6MtLEdrOl5TNFHbwKTl27/r9Cr2v2SNRE5bW/Hk
        2GgBCQIQWfkXqJLWEO3siio3jHMkkl3kPSnIRjhv0J2JKq0vDDohZMn0Ui8GpKr/
        XIHoK3cZpQTvrnWGCYlXi8jpYuevGeiGqdi2mfP6VeqJ+lsq4+S9A4uJ1nO+J75F
        ML1oJzwWrbX2rw==
        =EOZ3
        -----END PGP MESSAGE-----
      fp: 76459A92CB36A79D211C88FB35E5238BFB7C474A
  unencrypted_suffix: _unencrypted
  version: 3.7.3
