name: Kotlin CI

on:
  push:
    paths:
      - "app_kotlin/**"
  pull_request:
    paths:
      - "app_kotlin/**"
  workflow_dispatch:

jobs:
  buildlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build project
        working-directory: ./app_kotlin
        run: ./gradlew build

      - name: Check lint
        uses: "vroy/gha-kotlin-linter@v1"

  docker:
    needs: buildlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build ./app_kotlin -t dyllasdek/app_kotlin:latest

      - name: Push Docker image to DockerHub
        run: |
          docker push dyllasdek/app_kotlin:latest

  snyk:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Snyk
        uses: snyk/actions/gradle@master
        with:
          args: --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
