name: weather_app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app_go
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: app_go

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version:  '1.20'

      - name: Build
        run: go build -v .

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: app_go

      - name: Test
        run: go test -v .
  docker:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: Docker/login-action@v3
        with:
          username:  ${{  secrets.DOCKERHUB_USERNAME }}
          password:  ${{  secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app_go
          file: ./app_go/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/weather:latest